apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b9gsrpnny-python 
  janus-idp.io/tekton: b9gsrpnny-python
  backstage.io/kubernetes-id: b9gsrpnny-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b9gsrpnny-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml