apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: b9gsrpnny-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:30d3a4a8ae34bc6cd9f53daa5a5c95cd28e7fb1d@sha256:84425b6809f4433a0045fca8ac39c693efd25d76cd5241489edbd481173b789e
          name: container-image
